@InterviewWebApplication_HostAddress = http://localhost:5007

GET {{InterviewWebApplication_HostAddress}}/todos/
Accept: application/json

###

GET {{InterviewWebApplication_HostAddress}}/todos/1
Accept: application/json

###
